export class registro {
    id!:String;
    Nacionalidad_Titular!:String;
    Cedula_Titular!:String;
    Nombre_TItular_Beneficiario!:String;
    Apellido_TItular_Beneficiario!:String;
    Estado_Civil!:String;
    Sexo_Titular_Beneficiario!:String;
    Fecha_Nacimiento_Titular_Beneficiario!:String;
    Parentesco!:String;
    Nombre_Agente_Recaudador!:String;
    Tipo_de_Cuenta!:String;
    Numero_de_Cuenta!:String;
    Codigo_Cia_Seguro!:String;
    Tipo_de_Vencimiento!:String;
    Codigo_Empresa!:String;
    Codigo_Sucursal!:String;
    Numero_de_Telefono!:String;
    Correo_Electronico!:String;
    Codigo_Plan_en_SISER!:String;
    Codigo_Productor_Asesor!:String;
    Estado!:String;
    Estado_Observacion!:String;
}